services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_TLS_CERT: sans:localhost
      MP_SMTP_TLS_KEY: sans:localhost
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data

volumes:
  postgres_data:
  mailpit_data:
